<!--James Jackson-->
<!--ASD 1306-->
<!--Project 1-->
var json = {
	"0001": {
		"JobID":["Job ID","0001"],
		"clientID":["Client","Microsoft"],
		"address":["Address","123 Test Lane"],
		"city":["City","Redmond"],
		"state":["State","Wa"],
		"zipcode":["Zipcode","20722"],
		"phone":["Phone","000-000-0000"],
		"email":["Email","BillGates@microsoft.com"],
		"JobDate":["Job Date Date","20131001"],
		"incidentReponse":["Incident Response","Yes"],
		"JobType":["Job Type","Basic-Job"],
		"additionalData":["Additional Data","Windows 8 forever"]
	},
	"0002": {
        "JobID":["Job ID","0002"],
        "clientID":["Client","Google"],
        "address":["Address","123 Test Lane"],
        "city":["City","Cupertino"],
        "state":["State","Ca"],
        "zipcode":["Zipcode","20722"],
        "phone":["Phone","000-000-0000"],
        "email":["Email","EricS@gmail.com"],
        "JobDate":["Job Date Date","20131002"],
        "incidentReponse":["Incident Response","Yes"],
        "JobType":["Job Type","Intermediate-Job"],
        "additionalData":["Additional Data","Long live Android"]
	},
	"0003": {
        "JobID":["Job ID","0003"],
        "clientID":["Client","Apple"],
        "address":["Address","123 Test Lane"],
        "city":["City","Cupertino"],
        "state":["State","Ca"],
        "zipcode":["Zipcode","20722"],
        "phone":["Phone","000-000-0000"],
        "email":["Email","BillG@microsoft.com"],
        "JobDate":["Job Date Date","20131003"],
        "incidentReponse":["Incident Response","Yes"],
        "JobType":["Job Type","Basic-Job"],
        "additionalData":["Additional Data","Iphone is dead..."]
	},
	"0004": {
        "JobID":["Job ID","0004"],
        "clientID":["Client","Sony"],
        "address":["Address","123 Test Lane"],
        "city":["City","Redmond"],
        "state":["State","Wa"],
        "zipcode":["Zipcode","20722"],
        "phone":["Phone","000-000-0000"],
        "email":["Email","BillG@microsoft.com"],
        "JobDate":["Job Date Date","20131004"],
        "incidentReponse":["Incident Response","Yes"],
        "JobType":["Job Type","Basic-Job"],
        "additionalData":["Additional Data","PS4 looks sick"]
	},
	"0005": {
        "JobID":["Job ID","0005"],
        "clientID":["Client","IBM"],
        "address":["Address","123 Test Lane"],
        "city":["City","Redmond"],
        "state":["State","Wa"],
        "zipcode":["Zipcode","20722"],
        "phone":["Phone","000-000-0000"],
        "email":["Email","BillG@microsoft.com"],
        "JobDate":["Job Date Date","20131015"],
        "incidentReponse":["Incident Response","Yes"],
        "JobType":["Job Type","Advanced-Job"],
        "additionalData":["Additional Data","IBM who?"]
	},
	"0006": {
        "JobID":["Job ID","0006"],
        "clientID":["Client","Cisco"],
        "address":["Address","123 Test Lane"],
        "city":["City","Redmond"],
        "state":["State","Wa"],
        "zipcode":["Zipcode","20722"],
        "phone":["Phone","000-000-0000"],
        "email":["Email","BillG@microsoft.com"],
        "JobDate":["Job Date Date","20131016"],
        "incidentReponse":["Incident Response","Yes"],
        "JobType":["Job Type","Advanced-Job"],
        "additionalData":["Additional Data","Most hacked router ever."]
	},
	"0007": {
        "JobID":["Job ID","0007"],
        "clientID":["Client","Dell"],
        "address":["Address","123 Test Lane"],
        "city":["City","Redmond"],
        "state":["State","Wa"],
        "zipcode":["Zipcode","20722"],
        "phone":["Phone","000-000-0000"],
        "email":["Email","BillG@microsoft.com"],
        "JobDate":["Job Date Date","20131017"],
        "incidentReponse":["Incident Response","Yes"],
        "JobType":["Job Type","Intermediate-Job"],
        "additionalData":["Additional Data","Dude..."]
	},
	"0008": {
        "JobID":["Job ID","0008"],
        "clientID":["Client","HP"],
        "address":["Address","123 Test Lane"],
        "city":["City","Redmond"],
        "state":["State","Wa"],
        "zipcode":["Zipcode","20722"],
        "phone":["Phone","000-000-0000"],
        "email":["Email","BillG@microsoft.com"],
        "JobDate":["Job Date Date","20131018"],
        "incidentReponse":["Incident Response","Yes"],
        "JobType":["Job Type","Advanced-Job"],
        "additionalData":["Additional Data","Now why did they by palm again?"]
	},
	"0009": {
        "JobID":["Job ID","0009"],
        "clientID":["Client","Linksys"],
        "address":["Address","123 Test Lane"],
        "city":["City","Redmond"],
        "state":["State","Wa"],
        "zipcode":["Zipcode","20722"],
        "phone":["Phone","000-000-0000"],
        "email":["Email","BillG@microsoft.com"],
        "JobDate":["Job Date Date","20131019"],
        "incidentReponse":["Incident Response","Yes"],
        "JobType":["Job Type","Basic-Job"],
        "additionalData":["Additional Data","My WRT solution."]
	},
	"0010": {
        "JobID":["Job ID","0010"],
        "clientID":["Client","Asus"],
        "address":["Address","123 Test Lane"],
        "city":["City","Redmond"],
        "state":["State","Wa"],
        "zipcode":["Zipcode","20722"],
        "phone":["Phone","000-000-0000"],
        "email":["Email","BillG@microsoft.com"],
        "JobDate":["Job Date Date","20131020"],
        "incidentReponse":["Incident Response","Yes"],
        "JobType":["Job Type","Advanced-Job"],
        "additionalData":["Additional Data","Awesome motherboards..."]
	}
}